# Generated by Django 5.2.4 on 2025-07-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('source', models.CharField(max_length=255)),
                ('mapping', models.CharField(blank=True, max_length=255, null=True)),
                ('gpu', models.IntegerField()),
                ('deinterlacing', models.CharField(blank=True, max_length=255, null=True)),
                ('stream_type', models.CharField(choices=[('mpeg2', 'MPEG2'), ('mpeg4', 'MPEG4'), ('h264', 'H264'), ('h265', 'H265')], max_length=20)),
                ('resolution', models.CharField(max_length=20)),
                ('output_codec', models.CharField(choices=[('h264', 'H264'), ('h265', 'H265')], max_length=20)),
                ('bitrate', models.CharField(max_length=20)),
                ('max_bitrate', models.CharField(max_length=20)),
                ('preset', models.CharField(choices=[('slow', 'Slow'), ('medium', 'Medium'), ('fast', 'Fast'), ('hq', 'HQ')], max_length=20)),
                ('output_stream', models.CharField(choices=[('HLS', 'HLS'), ('UDP', 'UDP'), ('MPD', 'MPD'), ('RTP', 'RTP'), ('TS', 'TS'), ('MP4', 'MP4')], max_length=10)),
                ('output_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('frame_rate', models.IntegerField()),
                ('audio_bitrate', models.CharField(max_length=20)),
                ('audio_volume', models.IntegerField()),
                ('audio_codec', models.CharField(choices=[('AAC', 'AAC'), ('AC3', 'AC3'), ('MP3', 'MP3'), ('MP2', 'MP2')], max_length=10)),
                ('is_running', models.BooleanField(default=False)),
            ],
        ),
    ]
