# Generated by Django 5.2.1 on 2025-07-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='output_stream',
            field=models.CharField(choices=[('HLS', 'HLS'), ('MPD', 'MPD')], max_length=10),
        ),
    ]
