# Generated by Django 5.2.4 on 2025-07-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0002_alter_stream_output_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='gpu',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
